# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/io.xdc

# Block Designs: bd/BD/BD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD || ORIG_REF_NAME==BD} -quiet] -quiet

# IP: bd/BD/ip/BD_AXI4Stream_UART_0_0/BD_AXI4Stream_UART_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_AXI4Stream_UART_0_0 || ORIG_REF_NAME==BD_AXI4Stream_UART_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_axi4stream_spi_master_0_0/BD_axi4stream_spi_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_axi4stream_spi_master_0_0 || ORIG_REF_NAME==BD_axi4stream_spi_master_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_clk_wiz_0_0/BD_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_clk_wiz_0_0 || ORIG_REF_NAME==BD_clk_wiz_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_digilent_jstk2_0_0/BD_digilent_jstk2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_digilent_jstk2_0_0 || ORIG_REF_NAME==BD_digilent_jstk2_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_jstk_uart_bridge_0_0/BD_jstk_uart_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_jstk_uart_bridge_0_0 || ORIG_REF_NAME==BD_jstk_uart_bridge_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_proc_sys_reset_0_0/BD_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_proc_sys_reset_0_0 || ORIG_REF_NAME==BD_proc_sys_reset_0_0} -quiet] -quiet

# XDC: c:/Users/alija/Joystick_Interface/Joystick_Interface.gen/sources_1/bd/BD/BD_ooc.xdc
