# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pins.xdc

# Block Designs: bd/BD/BD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD || ORIG_REF_NAME==BD} -quiet] -quiet

# IP: bd/BD/ip/BD_clk_wiz_0_0/BD_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_clk_wiz_0_0 || ORIG_REF_NAME==BD_clk_wiz_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_proc_sys_reset_0_0/BD_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_proc_sys_reset_0_0 || ORIG_REF_NAME==BD_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_proc_sys_reset_1_0/BD_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_proc_sys_reset_1_0 || ORIG_REF_NAME==BD_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/BD/ip/BD_debouncer_0_0/BD_debouncer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_debouncer_0_0 || ORIG_REF_NAME==BD_debouncer_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_debouncer_1_0/BD_debouncer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_debouncer_1_0 || ORIG_REF_NAME==BD_debouncer_1_0} -quiet] -quiet

# IP: bd/BD/ip/BD_edge_detector_0_0/BD_edge_detector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_edge_detector_0_0 || ORIG_REF_NAME==BD_edge_detector_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_edge_detector_1_0/BD_edge_detector_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_edge_detector_1_0 || ORIG_REF_NAME==BD_edge_detector_1_0} -quiet] -quiet

# IP: bd/BD/ip/BD_digilent_jstk2_0_0/BD_digilent_jstk2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_digilent_jstk2_0_0 || ORIG_REF_NAME==BD_digilent_jstk2_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_axi4stream_spi_master_0_0/BD_axi4stream_spi_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_axi4stream_spi_master_0_0 || ORIG_REF_NAME==BD_axi4stream_spi_master_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_axis_dual_i2s_0_0/BD_axis_dual_i2s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_axis_dual_i2s_0_0 || ORIG_REF_NAME==BD_axis_dual_i2s_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_Mute_controller_0_0/BD_Mute_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_Mute_controller_0_0 || ORIG_REF_NAME==BD_Mute_controller_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_Toggle_reg_0_0/BD_Toggle_reg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_Toggle_reg_0_0 || ORIG_REF_NAME==BD_Toggle_reg_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_Toggle_reg_1_0/BD_Toggle_reg_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_Toggle_reg_1_0 || ORIG_REF_NAME==BD_Toggle_reg_1_0} -quiet] -quiet

# IP: bd/BD/ip/BD_LED_controller_0_0/BD_LED_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_LED_controller_0_0 || ORIG_REF_NAME==BD_LED_controller_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_Volume_controller_0_0/BD_Volume_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_Volume_controller_0_0 || ORIG_REF_NAME==BD_Volume_controller_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_Balance_controller_0_0/BD_Balance_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_Balance_controller_0_0 || ORIG_REF_NAME==BD_Balance_controller_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_Moving_average_filter_0_0/BD_Moving_average_filter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_Moving_average_filter_0_0 || ORIG_REF_NAME==BD_Moving_average_filter_0_0} -quiet] -quiet

# XDC: c:/Users/alija/Audio/Audio.gen/sources_1/bd/BD/BD_ooc.xdc
